server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: productService
          uri: http://localhost:8081/
          predicates:
            - Path=/product/**

        - id: userService
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**